### ISSUE TITLE
My desktop has too many files

### ISSUE THREAD

**Issue by kuguy400** [LeviOP/Canvas-Multi-File-Upload#3]
help my desktop has to many files on it

**Comment by Kangakc** [comment]
I had this same issue, thanks for posting! @LeviOP can you please fix this please instead of ignoring us!!!!!!!!!!!!!!!!!!

**Comment by LeviOP** [comment]
If your desktop has too many files, consider deleting the files if you no longer need them, or moving them to another location, like a folder, instead.

**Comment by kuguy400** [comment]
thanks levi, that worked!
